### ISSUE TITLE
Question about the --step command line argument 

### ISSUE THREAD

**Issue by FerdinandKlingenberg** [CNES/demcompare#1]
Hi,

I try to use the --step command line argument, but I get only errors.
I provided this command:
`demcompare --step coregistration test_config.json`

And I get this error:
`usage: demcompare [-h] [--step {coregistration,stats,report} [{coregistration,stats,report} ...]] [--display] [--version] config.json
demcompare: error: argument --step: invalid choice: 'config.json' (choose from 'coregistration', 'stats', 'report')`

The same happen with _stats_ and _report_, but when I skip the --step line argument, it works fine. 
Demcompare work all fine when I skip the --step line argument, but I want to execute only a subset of the whole process.

Other info:
The version of demcompare is:  0.1.0
And my _test_config.json_ file is attached (as .txt file, because file limitation from Github)
[test_config.txt](https://github.com/CNES/demcompare/files/6553709/test_config.txt)

Kind regards,
Ferdinand Klingenberg

**Comment by duboise-cnes** [comment]
Hello @FerdinandKlingenberg , sorry for the late reply, I didn't see the issue in my email. 

Indeed, the usage of step cannot be made easily before the config.json as the config.json is taken as a step and crash the command line. We cannot easily deal with this argparse problem for now (we could change the API to have no mandatory argument but this not foreseen yet). 

Please use demcompare test_config.json --step coregistration or demcompare --step coregistration -- test_config.json to make the command works. 

Thanks for the  test and sharing your problem. 
Emmanuel Dubois

**Comment by duboise-cnes** [comment]
This problem is also documented in README file : https://gitlab.cnes.fr/cars/demcompare#step-by-step-processing 
I close the issue accordingly. 
Cordially, 
Emmanuel
